### ISSUE TITLE
User Search Food

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#10]

**Comment by hungbkdn** [comment]
![usersearchfood](https://user-images.githubusercontent.com/26675245/28651225-b91b726c-72aa-11e7-8a8e-3abc8d43562c.jpg)

**Comment by ghost** [comment]
-you should change user:User to :User, items:Items to :Item
-you should change food:View to GUI:<viewName>
-you have to dissociation WebServer to multi object.

**Comment by hungbkdn** [comment]
![userSearchFood.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46fd879f31b186a89deab765ab52f4d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ed3823e28c8f47361c1755.jpg)

**Comment by ghost** [comment]
-:Foods change to :Food.

**Comment by hungbkdn** [comment]
I updated, please check it again
Thank you so much
![userSearchFood.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46fd879f31b186a89deab765ab52f4d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ed3a22e78b874d3c1b1755.jpg)

**Comment by ghost** [comment]
LGTM
