### ISSUE TITLE
Guest - Register - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#11]
Draw sequence diagram

**Comment by at-vudang95** [comment]
Sequence diagram use case register
![register.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fa919d2a9197ac9dabf301b44fff9e2c4533317346f6722681b579be477e0009094aaa41585e15aafeda79f0e72e6c981e5ab38532022d8c6853beb2901db90bbb258b4f80b5bb834ec6ee3427f5c6.jpg)

**Comment by ghost** [comment]
-you should change guest1:Guest to :Guest, user:User to :User
-you should change register:Page to GUI:
-you have to split WebServer to multi object.
-miss method save.
-you should define methods with params in sequence diagram.

**Comment by at-vudang95** [comment]
Please you check again! Thank you!
![register.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fa919d2a9197ac9dabf301b44fff9e2c4533317346f6722681b579be477e0009094aaa41585e15aafeda79f0e72e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4f83b4be824bc2ee3b23f5c6.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-remove display functions
-remove frame connect database
-from controller call model by create function, and model save by itself.
-miss validate function
-(9) should call by :User.
-remove display error functions

**Comment by at-vudang95** [comment]
![register.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fa919d2a9197ac9dabf301b44fff9e2c4533317346f6722681b579be477e0009094aaa41585e15aafeda79f0e72e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4f8db4ba8845c5e93425f5c6.jpg)
I checked, please you check again, thank you!

**Comment by ghost** [comment]
-(9) what will happen when (8) was error?

**Comment by at-vudang95** [comment]
![register.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fa919d2a9197ac9dabf301b44fff9e2c4533317346f6722681b579be477e0009094aaa41585e15aafeda79f0e72e6c981e5ab38532022d8c6853beb2901db90bbb258b4e84b4bb8e45c6ed3e2df5c6.jpg)
Please you check again! Thank you!

**Comment by ghost** [comment]
LGTM
