### ISSUE TITLE
Admin - View category - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#12]
Sequence Diagram

**Comment by at-vudang95** [comment]
Sequence Diagram View Category
![ReadCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46da919b27a182bd8ae5b044bd1fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8a4ac2eb3b2de48a894f2c53.jpg)

**Comment by ghost** [comment]
@at-vudang please check
- `:GUI` you should define the name of GUI
- Pagination should be handle in model ( or repository), not in controller.

**Comment by at-vudang95** [comment]
![viewcategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fe9d9f348182bd8aeeb051bd1fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8b49c7ef3427e28c8d462c53.jpg)
I updated. Please check it again. Thank you!

**Comment by ghost** [comment]
LGTM
