### ISSUE TITLE
Admin - View order - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#13]
Sequence Diagram

**Comment by at-vudang95** [comment]
Sequence Diagram View Manage Order Admin
![ViewOrder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46de9d9f34ad91ad8afbfd0fe64de29b234324676b5ee17e29d3e77eee437e040e0918a847585f45adaf8e78f4e06d62964e49bc8f3900299f7744eeaa880dbd07b0218e4f85b0be894ec9ec3a2de399c2.jpg)

**Comment by ghost** [comment]
-change :GUI to GUI:viewName.
-pagination function should be in Model.
-remove display List order.

**Comment by at-vudang95** [comment]
![vieworder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fe9d9f348d91ad8afbfd0fe64de29b234324676b5ee17e29d3e77eee437e040e0918a847585f45adaf8e78f4e06d62964e49bc8f3900299f7744eeaa880dbc00b0218e4f84b3bb8c4bc4e03920ee99c2.jpg)
I updated. Please check it again!

**Comment by ghost** [comment]
-(5) should be same (2).

**Comment by at-vudang95** [comment]
I update. Please you check it again!

**Comment by ghost** [comment]
LGTM
