### ISSUE TITLE
Guest Search Food

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#15]

**Comment by hungbkdn** [comment]
![guestSearchFood.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ef819f3096b0ac8efbbc4b8252ff906b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93820e28c8849371c070ac4.jpg)

**Comment by ghost** [comment]
-:Foods change to :Food

**Comment by hungbkdn** [comment]
I updated, please check it again
Thank you so much
![guestSearchFood.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ef819f3096b0ac8efbbc4b8252ff906b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93822e1828b4738180c0ac4.jpg)

**Comment by ghost** [comment]
LGTM
