### ISSUE TITLE
EER Diagram

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#19]
![eerHopeLastUpdate.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ed91880b8d93aca3e8ac57914df4953d43653f6b14b1247a80e03cfd18395456591aaa40090a11adafdf2fa0b63c71db0a0cbe833b0e66da2f53fde6d640e258f075c95d8fa4be8c46c1ed3d24e38c8d4a3e1c011c8ded10.png)

**Comment by ghost** [comment]
-Menu: menu_id change to id,
-Item should split to two table: foods and Material
-Category: category_id change to id
-User: user_id change to id
-You should create use_profile table.
-table name must plurality

**Comment by hungbkdn** [comment]
Thanks for your check!
I updated according to your requirement, please check it again :smiley:

**Comment by ghost** [comment]
- Column name MUST be unified in `camelCase` or `underscore`. Don't conflicts like: `isFood`, `custom_address`, `phonenumber`...
- Column `forFood` is wrong in `categories` table. It should be `isFood` or `is_food` because of data type.

[Reviewing...]

**Comment by hungbkdn** [comment]
> Column name MUST be unified in camelCase or underscore. Don't conflicts like: isFood, custom_address, phonenumber...
Column forFood is wrong in categories table. It should be isFood or is_food because of data type.
[Reviewing...]

I fixed it, please check it again.
thank you so much!

**Comment by ghost** [comment]
@at-hungnguyen Please let your members thinking about add `created_at`, `updated_at` and `deleted_at` column  for table. We must need these column to do something.

**Comment by hungbkdn** [comment]
I updated on the first comment, please check it
Thank you so much

**Comment by at-phucnguyen** [comment]
Feedback:
a @at-nguyenvo, @at-duyho @at-locbui Loc

1. Nên thêm trường deleled_at cho các bảng để sử dụng xoá mềm
2. Có nên tách bảng `admin` ra riêng, `user` ra riêng để tiện quản lý không?
3. Trường `image` nên để kiểu `varchar` thay vì kiểu `text` để tiết kiệm tài nguyên
4. Nên đổi tên bảng `food` thành `foods` để đồng bộ cách đặt tên
5. Nên thêm trường để biết được nguyên liệu của mỗi ngày còn bao nhiêu (kg hoặc số lượng)..

**Comment by hungbkdn** [comment]
@at-phucnguyen 
Em có sửa lại là thêm trường deleted_at cho các bảng, sửa image từ text->varchar(255) và đổi tên bảng food -> foods. 
Còn cái 5. thì yêu cầu chỉ có Thực đơn đồ ăn là dành cho hàng ngày thôi mà anh? Còn cái nguyên liệu là mặc định luôn có sẵn
Cái 4. thì để tiện sử dụng chức năng Authentication có sẵn trong Laravel nên tụi em dùng chung bảng User
Mấy anh xem lại giúp em
![eerHopeLastUpdate.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ed91880b8d93aca3e8ac57914df4953d43653f6b14b1247a80e03cfd18395456591aaa40090a11adafdf2fa0b63c71db0a0cbe833b0e66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d24e18e864e361a021f89ed10.png)

**Comment by at-phucnguyen** [comment]
@at-hungnguyen 
Vậy thì anh nghĩ nên thêm trường status để quản lý trong admin `còn hàng` hoặc `hết hàng`. Chứ có phải khi nào cũng còn đâu :D

**Comment by hungbkdn** [comment]
![eerHopeLastUpdate.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ed91880b8d93aca3e8ac57914df4953d43653f6b14b1247a80e03cfd18395456591aaa40090a11adafdf2fa0b63c71db0a0cbe833b0e66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d24e0898d4c3e160c118ded10.png)
@at-phucnguyen 
Em cập nhật lại rồi anh, anh xem lại giúp tụi em lần nữa :D

**Comment by at-phucnguyen** [comment]
@at-hungnguyen 
Anh thấy ok rồi đó, bảng nào có delete thì nên thêm deleted_at để xoá mềm hết nhé
