### ISSUE TITLE
Admin create material

### ISSUE THREAD

**Issue by vhhieu95** [AT-PHPIntership/food-market-order#21]
Sequence Manage Material

**Comment by vhhieu95** [comment]
![creatmaterial](https://user-images.githubusercontent.com/29418860/28706149-2949faa2-739d-11e7-9544-e2a83d986b9e.jpg)

**Comment by ghost** [comment]
@at-hieuvo 
- Point 2 : GetFormAdd() please make clearly the name like `request get form` or something...
- Point 11: The model can't return to view without through controller. And which is return? success message or ...

**Comment by vhhieu95** [comment]
![creatmaterial2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46eb869f22968ea89becad4aa551a2d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ed3a2ce48a8f4d3e1a1755.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
LGTM.
