### ISSUE TITLE
Admin create food

### ISSUE THREAD

**Issue by vhhieu95** [AT-PHPIntership/food-market-order#22]
Sequence Manage Food

**Comment by vhhieu95** [comment]
![creatfood](https://user-images.githubusercontent.com/29418860/28460198-2cf54c36-6e3b-11e7-94a9-87177dd917ab.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-in sequence diagram you can use more than one view.
-(7) you should use same (3)

**Comment by vhhieu95** [comment]
![creatfood](https://user-images.githubusercontent.com/29418860/28512337-b38696aa-707b-11e7-8587-800d0c2311a0.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-what will happen when (9) was error?

**Comment by vhhieu95** [comment]
![creatfood](https://user-images.githubusercontent.com/29418860/28706124-15ef5646-739d-11e7-8cc6-b60c25f5adb2.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-(9) you don't return from model to view.

**Comment by vhhieu95** [comment]
![creatfood.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46eb869f229685a680edfd0fe64de29b234324676b5ee17e29d3e77eee437e040e0918a847585f45adaf8e78f4e06d62964e49bc8f3900299f7744eeaa880dbd07b0218e4f84b3bb8f48c1ef3526e199c2.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
-(8) same (35).
-(2) should be an action.

**Comment by vhhieu95** [comment]
![creatfood2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46eb869f229685a680eded01e81fe086264c22703d46f96925dcb52ce9137a040a0e18fa455e5f44fda8df2cf5e46a21984019af80330b2b9b645bf9fa9015ad02bb2a8a4a85b7b98d45c0e03d2de08a9d02.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
LGTM
