### ISSUE TITLE
Admin read food

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#23]
sequence dialgram

**Comment by vhhieu95** [comment]
![readfood](https://user-images.githubusercontent.com/29418860/28460190-1f80dcfa-6e3b-11e7-91cc-991bc55ff323.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-You should change admin:Admin to :Admin
-getAllFood($id)? I don't understand this function?
-remove showList function.
-you should create get list food sequence diagram.

**Comment by vhhieu95** [comment]
![readfood](https://user-images.githubusercontent.com/29418860/28512323-9f49dd96-707b-11e7-9bc4-a5f7b3037417.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-remove showList function.

**Comment by vhhieu95** [comment]
![readfood](https://user-images.githubusercontent.com/29418860/28706112-0a74fffa-739d-11e7-8c1d-4b3999264332.jpg)
I updated. Please you check again!
