### ISSUE TITLE
Admin Update food

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#24]
sequence diagram

**Comment by vhhieu95** [comment]
![updatefood](https://user-images.githubusercontent.com/29418860/28453072-b965ebec-6e1f-11e7-88fc-1b70cdbbf9b9.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-remove function showView, showError.
-change  show Update Success to return success.
-change GetIdFood() to getFood($id) and get it from Item

**Comment by vhhieu95** [comment]
![updatefood](https://user-images.githubusercontent.com/29418860/28460040-68fe449a-6e3a-11e7-91e5-d1a66a4a5964.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-you should change admin:Admin to :Admin
-you should change :GUI to GUI:viewName. please change it. thank you.

**Comment by vhhieu95** [comment]
![updatefood](https://user-images.githubusercontent.com/29418860/28512227-2fe8723c-707b-11e7-95b8-4feec7c3d964.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-remove function Show Error
-what will happen when (9) was error.

**Comment by vhhieu95** [comment]
![updatefood](https://user-images.githubusercontent.com/29418860/28706102-fdbd7148-739c-11e7-94a5-9fd9b356d229.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-(9), you don't return from model to view.

**Comment by vhhieu95** [comment]
![updatefoods.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46fd849e229686af80e6bb50e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8f4bc5ec3a2de2898e5d73.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
LGTM
