### ISSUE TITLE
Admin delete food

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#25]
sequence diagram

**Comment by vhhieu95** [comment]
![deletefood](https://user-images.githubusercontent.com/29418860/28706088-ec03f21a-739c-11e7-8851-d74b6054144c.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-(2), (3) should be outer fragment.
-(5) should be a action.
-(7) should don't return from Mode to View.

**Comment by vhhieu95** [comment]
please check my update again, thank you!
![deletefood2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46ec9196269686af80e6bb11e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8f4bc9eb3b26e58e875d73.jpg)

**Comment by ghost** [comment]
@at-hieuvo Missing action (5)

**Comment by vhhieu95** [comment]
![deletefood3.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46ec9196269686af80e6bb10e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b826814e80b6bd8f44c2ed3e20e3838d5d73.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
LGTM
