### ISSUE TITLE
Admin read material

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#26]
sequence diagram

**Comment by vhhieu95** [comment]
![readmaterial](https://user-images.githubusercontent.com/29418860/28453049-9db92c10-6e1f-11e7-8c60-e7acd1b8da66.jpg)

**Comment by ghost** [comment]
-you should change admin:Admin to :Admin
-you should change :GUI to GUI:viewName. please change it. thank you.
-remove showList function

**Comment by vhhieu95** [comment]
![readmaterial](https://user-images.githubusercontent.com/29418860/28512184-f9b4d9bc-707a-11e7-847d-257a2551e961.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-remove showList function

**Comment by vhhieu95** [comment]
![readmaterial](https://user-images.githubusercontent.com/29418860/28706050-c3726f02-739c-11e7-8fd7-3e3bd4afbee8.jpg)
I updated. Please you check again!
