### ISSUE TITLE
Admin delete material

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#27]
sequence diagram

**Comment by vhhieu95** [comment]
![deletematerial](https://user-images.githubusercontent.com/29418860/28706070-de4541b0-739c-11e7-8b65-697b5d0ff41b.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-(2), (3) should be outer fragment.
-(5) should be a action.
-(7) don't return from Model to View.

**Comment by vhhieu95** [comment]
![deletematerial.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46ec9196269686a48efdba51ad5cfcd665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ed3a20e4838d4e381b1755.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
-(1) change clickButtonDelete().

**Comment by vhhieu95** [comment]
![deleteMaterial.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46ec9196269686848efdba51ad5cfcd665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ed3a2ce5888f4c3c1a1755.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
LGTM
