### ISSUE TITLE
Admin - Manage Daily Menu - Update Menu 

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#28]
![adminupdatemenu](https://user-images.githubusercontent.com/26675245/28651089-de4fbbf2-72a9-11e7-9d35-87527fb961fd.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-you should change (1) onClick(): update to onClick()
-remove show update: view, displayError.

**Comment by ghost** [comment]
-change GUI:menuList: to GUI:menuList
-what will happen when (8) was error.

**Comment by hungbkdn** [comment]
![adminupdatemenu](https://user-images.githubusercontent.com/26675245/28654147-3ca742e4-72bc-11e7-975b-034fbee8f222.jpg)

I updated, please check my comment!
Thank you so much

**Comment by ghost** [comment]
(3), (10) should be same (7).

**Comment by hungbkdn** [comment]
![adminUpdateMenu.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46e990972a8cb6b98be8ab468958fe816b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93820e18f8d47371d050ac4.jpg)
I updated, please check it again
Thank you so much

**Comment by ghost** [comment]
-(2), (5) should be a action.

**Comment by hungbkdn** [comment]
![adminUpdateMenu.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46e990972a8cb6b98be8ab468958fe816b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93823e08986483d1a020ac4.jpg)
I updated, please check it again
Thank you so much

**Comment by ghost** [comment]
LGTM
