### ISSUE TITLE
Admin - Manage Daily Menu - Read Menu 

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#29]
![adminreadmenu](https://user-images.githubusercontent.com/26675245/28651081-d6b26ef8-72a9-11e7-831d-31c9eea6c198.jpg)

**Comment by ghost** [comment]
@at-hungnguyen 
- Point 3, you should add the verb like `get all menu`
- And change the title `Menu Detail` to make clearly, not `Read Menu` :)

**Comment by hungbkdn** [comment]
![adminReadMenu.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46e990972a8cb1ac8eed9246aa48b2d86b56357c2301a03f32dfa17de6147f575e0e1bf9100e0940faf9892af7e03b23d80a5affcd7f1d2598694ef1e1c84afd13b03289498fb7b98a4dc5ee3a20e08e8e4e3c0c48.jpg)
I updated, please check it again
Thank you so much

**Comment by ghost** [comment]
LGTM.
