### ISSUE TITLE
Use-case diagram

### ISSUE THREAD

**Issue by ghost** [AT-PHPIntership/food-market-order#3]
Use-case diagram

**Comment by dungvan** [comment]
#  overview use-case diagram
![usecase_overview](https://user-images.githubusercontent.com/29423561/28448548-f8104594-6e02-11e7-9c25-22e1598ce595.jpg)
## Admin use-case
![managedailymenuusecase](https://user-images.githubusercontent.com/19891027/28447631-2363df82-6dfc-11e7-891f-91f30e68e472.jpg)
![managefoodusecase](https://user-images.githubusercontent.com/19891027/28447632-284722c0-6dfc-11e7-8f7f-1bf8c35cdd8d.jpg)
![adminmanageusers](https://user-images.githubusercontent.com/26675245/28447655-64b712c4-6dfc-11e7-89e2-734413cb4ec7.jpg)
![adminmanagecategories](https://user-images.githubusercontent.com/26675245/28458543-45333c88-6e34-11e7-9abd-647bd2aa7556.jpg)

![usecasematerial](https://user-images.githubusercontent.com/29418860/28448484-960084fe-6e02-11e7-9d9c-2418b10c4af8.jpg)
![usecaseorder](https://user-images.githubusercontent.com/29418860/28453250-bb93bc86-6e20-11e7-887b-205c7fe5e208.jpg)



## user use-case

![use-case view](https://user-images.githubusercontent.com/11406553/28447606-eb76fa14-6dfb-11e7-96ee-aa7716892754.jpg)
![manageprofile](https://user-images.githubusercontent.com/29423561/28448560-066baac0-6e03-11e7-89f5-dfd9a1d850f3.jpg)
![order](https://user-images.githubusercontent.com/29423561/28448561-066da3c0-6e03-11e7-9bc7-919bbff84573.jpg)

# Break down
|    Actor     |    Use case     |      Action      |
| :----------: | :-------------: | :--------------: |
|    Admin     |  Manage Users   |      Create      |
|    Admin     |  Manage Users   |       Read       |
|    Admin     |  Manage Users   |      Update      |
|    Admin     |  Manage Users   |      Delete      |
|    Admin     | Manage Category |      Create      |
|    Admin     | Manage Category |       Read       |
|    Admin     | Manage Category |      Update      |
|    Admin     | Manage Category |      Delete      |
|    Admin     |  Manage Order   |       Read       |
|    Admin     |  Manage Order   |      Delete      |
|    Admin     |   Manage Menu   |      Create      |
|    Admin     |   Manage Menu   |       Read       |
|    Admin     |   Manage Menu   |      Update      |
|    Admin     |   Manage Menu   |      Delete      |
|    Admin     |   Manage Food   |      Create      |
|    Admin     |   Manage Food   |       Read       |
|    Admin     |   Manage Food   |      Update      |
|    Admin     |   Manage Food   |      Delete      |
|    Admin     | Manage Material |      Create      |
|    Admin     | Manage Material |       Read       |
|    Admin     | Manage Material |      Update      |
|    Admin     | Manage Material |      Delete      |
| Admin,  User |   Choose Food   |      Create      |
| Admin,  User |   Choose Food   |      Delete      |
| Admin,  User |   Order Food    |     Confirm      |
| Admin,  User |   Order Food    |      Cancel      |
| Admin,  User | Choose Material |      Create      |
| Admin,  User | Choose Material |      Delete      |
| Admin,  User | Order Material  |     Confirm      |
| Admin,  User | Order Material  |      Cancel      |
| User,  Guest |    View Material    |      Search      |
| User,  Guest |    View Material    | Read detail item |
| User,  Guest |    View Food    |      Search      |
| User,  Guest |    View Food    | Read detail item |
|    Guest     |    Registry     |     Registry     |

# use case description

### Register

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào trang đăng ký </td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút đăng ký mà chuyển trang hoặc tắt trình duyệt , use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng đăng ký account đăng nhập vào hệ thống </td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Điền đầy đủ vào các trường với username, email và password là bắt buộc</td>
        <td><b>- check validate các trường bắt buộc.</b><br/>
        + Nếu không có lỗi thì insert vào cơ sở dữ liệu. Nếu insert thành công thông báo đăng ký thành công và trả về trang đăng nhập, ngược lại thông báo lỗi</br>
        + Nếu check validate không thàng công thì thông báo lỗi.
        </td>
    </tr>
</table>

### Login

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">User,Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Chưa ở trạng thái đăng nhập ứng dụng</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng đăng nhập vào hệ thống để có thể giao dịch với hệ thống</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào liên kết đăng nhập ở góc phải màn hình.</br>- Nhập thông tin username và password vào ô nhập liệu. Sau đó nhấn nút đăng nhập.</td>
        <td>- Chuyển người dùng đến trang đăng nhập. <br/>- Lấy thông tin. Kiểm tra hợp lệ. <br/>- Nếu thành công hệ thống khởi tạo phiên làm việc với tài khoản trên. Ngược lại, hệ thống ở trang đăng nhập
        </td>
    </tr>
</table>


## 1. Manage Users

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>	
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Quản trị viên có thể quản lý các user đã đăng ký tài khoản trong hệ thống. Bao gồm các hành động: Xem chi tiết, Tìm kiếm, Lọc, Thêmmới, Chỉnh Sửa, Xóa User.</td>
    </tr>
    <tr>
        <td rowspan="10">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>
        Create User:
	<p>- Người quản trị nhấn vào nút Thêm</p>
	<p>- Nhập thông tin vào form thêm mới</p>
	<p>- Nhấn nút lưu để thêm mới user vào cơ sở dữ liệu</p>
	</td>
        <td>
        <br>
	<p>- Hệ thống hiện thị form thêm user để người quản trị nhập thông tin.</p>
	<br>
	<p>- Nếu thành công, trả về thông báo thêm thành công, quay lại trang quản lý user. Ngược lại thông báo thêm mới user không thành công.</p>
        </td>
    </tr>
    <tr>
    	<td>
    	Read User:
    	<p> - Người quản trị có thể nhấn vào tên user trên cột user hoặc vào biểu tượng xem chi tiết trên mỗi dòng</p>
    	</td>
    	<td>
	- Hệ thống chuyển đến trang chi tiết user.
    	</td>
    </tr>
    <tr>
    	<td>
    	*Update User:
    	<p>- Người quản trị nhấn vào nút Sửa ở cột chức năng.</p>
    	<p>- Nhập thông tin vào form sửa.</p>
    	<p>- Nhấn nút lưu để cập nhật thông tin user vào cơ sở dữ liệu.</p>
    	</td>
    	<td>
    	<p><br></p>
    	<p>- Hệ thống hiện thị form sửa user để người quản trị nhập thông tin.</p>
    	<p>-</p>
    	<p>- Nếu thành công, trả về thông báo cập nhật thành công, quay lại trang quản lý user. Ngược lại thông báo cập nhật user không thành công</p>
    	</td>
    </tr>
    <tr>
    	<td>
    	* Delete User:
    	<p>- Người quản trị nhấn vào nút Xóa ở cột chức năng hoặc đánh dấu tích vào ô check box ở đầu dòng chứa mỗi user. Sau đó nhấn nút Xóa.</p>
    	</td>
    	<td>
    	- Nếu thành công, trả về thông báo xóa thành công, quay lại trang quản lý user. Ngược lại thông báo xóa user không thành công.
    	</td>
    </tr>
</table>

## 2.Manage categories

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>	
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Quản trị viên có thể quản lý các danh mục nguyên liệu và thức ăn của chức năng đặt hàng trong hệ thống. Bao gồm các hành động: Xem chi tiết,  Thêm mới, Chỉnh Sửa, Xóa Danh mục.</td>
    </tr>
    <tr>
        <td rowspan="10">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>
        Create Category:
	<p>- Người quản trị nhấn vào nút Thêm</p>
	<p>- Nhập thông tin vào form thêm mới</p>
	<p>- Nhấn nút lưu để thêm mới danh mục vào cơ sở dữ liệu</p>
	</td>
        <td>
        <br>
	<p>- Hệ thống hiện thị form thêm danh mục để người quản trị nhập thông tin.</p>
	<br>
	<p>- Nếu thành công, trả về thông báo thêm thành công, quay lại trang quản lý danh mục. Ngược lại thông báo thêm mới danh mục không thành công.</p>
        </td>
    </tr>
    <tr>
    	<td>
    	Read Category:
    	<p> - Người quản trị có thể nhấn vào tên danh mục trên cột danh mục hoặc vào biểu tượng xem chi tiết trên mỗi dòng</p>
    	</td>
    	<td>
	- Hệ thống chuyển đến trang chi tiết danh mục.
    	</td>
    </tr>
    <tr>
    	<td>
    	*Update Category:
    	<p>- Người quản trị nhấn vào nút Sửa ở cột chức năng.</p>
    	<p>- Nhập thông tin vào form sửa.</p>
    	<p>- Nhấn nút lưu để cập nhật thông tin danh mục vào cơ sở dữ liệu.</p>
    	</td>
    	<td>
    	<p><br></p>
    	<p>- Hệ thống hiện thị form sửa danh mục để người quản trị nhập thông tin.</p>
    	<p>-</p>
    	<p>- Nếu thành công, trả về thông báo sửa thành công, quay lại trang quản lý danh mục. Ngược lại thông báo sửa danh mục không thành công</p>
    	</td>
    </tr>
    <tr>
    	<td>
    	* Delete Category:
    	<p>- Người quản trị nhấn vào nút Xóa ở cột chức năng hoặc đánh dấu tích vào ô check box ở đầu dòng chứa mỗi danh mục. Sau đó nhấn nút Xóa.</p>
    	</td>
    	<td>
    	- Nếu thành công, trả về thông báo xóa thành công, quay lại trang quản lý danh mục. Ngược lại thông báo xóa danh m không thành công.
    	</td>
    </tr>
</table>

## 3.Manage Orders

**3.1 Confirm Order

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống và đã nhập địa chỉ nhận hàng.</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng nhấn nút đặt hàng để xác nhận đơn hàng với hệ thống.</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style="width: 30%;vertical-align : top;">- Nhấn vào nút đặt hàng.
        </td>
        <td>- Lấy thông tin. <br/>- Nếu thành công hệ thống cập nhật đơn hàng vào cơ sở dữ liệu và thông báo thành công ở trang người dùng. Ngược lại trả về thông báo đặt hàng thất bại ở trang người dùng
        </td>
    </tr>
</table>

**3.2 Cancel Order

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống và đã nhập địa chỉ nhận hàng.</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng nhấn nút hủy để xác nhận hủy đơn hàng với hệ thống.</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style="width: 30%;vertical-align : top;">- Nhấn vào nút hủy.
        </td>
        <td> Hủy giỏ hàng đã chọn và trở về trang người dùng.
        </td>
    </tr>
</table>


## 4.Manage Daily Menu

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Log out </td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Quản trị viên có thể quản lý các thực đơn của chức năng đặt cơm trong hệ thống. Bao gồm các hành động: Xem chi tiết, Tìm kiếm, Thêm mới, Chỉnh Sửa, Xóa Thực đơn.  </td>
    </tr>
    <tr>
        <td rowspan="7">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
   <tr>
        <td style='vertical-align : top; '>
Thêm mới thực đơn:
<br>- Người quản trị nhấn vào nút Thêm
<br>- Nhập thông tin vào form thêm mới<br>
- Nhấn nút lưu để thêm mới thực đơn vào cơ sở dữ liệu</td>
        <td>- Hệ thống hiện thị form thêm thực đơn để người quản trị nhập thông tin.<br>
- Nếu thành công, trả về thông báo thêm thành công, quay lại trang quản lý thực đơn. Ngược lại thông báo thêm mới thực đơn không thành công.
        </td>
    </tr>
    <tr>
        <td style='vertical-align : top; '>
Sửa thực đơn:
<br>- Người quản trị nhấn vào nút Sửa ở cột chức năng.
<br>- Nhập thông tin vào form sửa.
- Nhấn nút lưu để cập nhật thông tin thực đơn vào cơ sở dữ liệu</td>
        <td> 
<br>- Hệ thống hiện thị form sửa thực đơn để người quản trị nhập thông tin.
<br>- Nếu thành công, trả về thông báo cập nhật thành công, quay lại trang quản lý thực đơn. Ngược lại thông báo cập nhật thực đơn không thành công.</td>
    </tr>
     <tr>
        <td style='vertical-align : top; '>
Xóa thực đơn:
<br>- Người quản trị nhấn vào nút Xóa ở cột chức năng hoặc đánh dấu tích vào ô check box ở đầu dòng chứa mỗi thực đơn. Sau đó nhấn nút Xóa.</td>
        <td> 
- Nếu thành công, trả về thông báo xóa thành công, quay lại trang quản lý thực đơn. Ngược lại thông báo xóa thực đơn không thành công.</td>
    </tr>    
</table>


## 5.Manage Food
<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Log out</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Quản trị viên có thể quản lý các món ăn của chức năng đặt cơm trong hệ thống. Bao gồm các hành động: Xem chi tiết, Tìm kiếm, Lọc, Thêm mới, Chỉnh Sửa, Xóa Món ăn.  </td>
    </tr>
    <tr>
        <td rowspan="7">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
   <tr><td style='vertical-align : top; '>-Xem chi tiết món ăn:<br>Người quản trị có thể nhấn vào tên món ăn trên cột nhóm hoặc vào biểu tượng xem chi tiết trên mỗi dòng.</td>
     <td>- Hệ thống chuyển đến trang chi tiết món ăn.</td>
    </tr>
    <tr>
        <td style='vertical-align : top; '>-Tìm kiếm món ăn:- Người quản trị nhập tên món ăn cần tìm kiếm vào ô tìm kiếm và nhấn nút search.</td>
        <td> - Hệ thống tìm kiếm tên món ăn trong cơ sở dữ liệu.<br>-Nếu tìm thấy, hệ thống hiển thị danh sách kết quả lên màn hình.<br>- Ngược lại, hệ thống hiển thị lên màn hình, không tìm thấy dữ liệu.</td>
    </tr>
     <tr>
        <td style='vertical-align : top; '>Thêm mới món ăn:<br>- Người quản trị nhấn vào nút Thêm<br>- Nhập thông tin vào form thêm mới- Nhấn nút lưu để thêm mới món ăn vào cơ sở dữ liệu</td>
        <td> - Hệ thống hiện thị form thêm món ăn để người quản trị nhập thông tin.<br>- Nếu thành công, trả về thông báo thêm thành công, quay lại trang quản lý món ăn. Ngược lại thông báo thêm mới món ăn không thành công.</td>
    </tr>
     <tr>
        <td style='vertical-align : top; '>Sửa món ăn:<br>- Người quản trị nhấn vào nút Sửa ở cột chức năng.<br>- Nhập thông tin vào form sửa.<br>- Nhấn nút lưu để cập nhật thông tin món ăn vào cơ sở dữ liệu.</td>
        <td> - Hệ thống hiện thị form sửa món ăn để người quản trị nhập thông tin.- Nếu thành công, trả về thông báo cập nhật thành công, quay lại trang quản lý món ăn. Ngược lại thông báo cập nhật món ăn không thành công.
</td>
    </tr>
     <tr>
        <td style='vertical-align : top; '> Xóa món ăn:- Người quản trị nhấn vào nút Xóa ở cột chức năng hoặc đánh dấu tích vào ô check box ở đầu dòng chứa mỗi món ăn. Sau đó nhấn nút Xóa.</td>
        <td> - Nếu thành công, trả về thông báo xóa thành công, quay lại trang quản lý món ăn. Ngược lại thông báo xóa món ăn không thành công.
</td>
    </tr>
</table>



## 6.Manage Material

## 7.View Food

**7.1 Search Food**

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào trang món ăn</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút tìm kiếm mà chuyển trang hoặc tắt trình duyệt , use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng tìm kiếm món ăn theo tên hoặc thể loại hoặc giá cả  </td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- chọn phương thức tìm kiếm theo tên hoặc thể loại hoặc giá cả rồi nhấn nút tìm kiếm</td>
        <td>- Lấy thông tin và kiểm tra trong cơ sở dữ liệu xem có món ăn nào phù hợp điều kiện tìm kiếm của người dùng. <br/>- Nếu có trả về danh sách món ăn thõa mãn, ngược lại thông báo không tìm thấy.
        </td>
    </tr>
</table>

**7.2 View Detail Food**

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào trang món ăn </td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút xem chi tiết mà chuyển trang hoặc tắt trình duyệt , use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng tìm xem chi món ăn: tên, giá cả, thể loại, mô tả,...  </td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- nhấn vào xem chi tiết của món ăn cụ thể</td>
        <td>- Lấy thông tin món ăn trong cơ sở dữ liệu.<br/>
        - Nếu thành công trả về trang chi tiết món ăn, ngược lại thông báo lỗi.
        </td>
    </tr>
</table>

## 8.View Material
**8.1 Search Material**

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào trang nguyên liệu </td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút tìm kiếm mà chuyển trang hoặc tắt trình duyệt , use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng tìm kiếm nguyên liệu theo tên hoặc thể loại hoặc giá cả  </td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- chọn phương thức tìm kiếm theo tên hoặc thể loại hoặc giá cả rồi nhấn nút tìm kiếm</td>
        <td>- Lấy thông tin và kiểm tra trong cơ sở dữ liệu xem có nguyên liệu nào phù hợp điều kiện tìm kiếm của người dùng. <br/>- Nếu có trả về danh sách nguyên liệu thõa mãn, ngược lại thông báo không tìm thấy.
        </td>
    </tr>
</table>

**7.3 Choose Food

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đang ở trạng thái đăng nhập ứng dụng</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Thêm hoặc hủy món ăn vào giỏ hàng đặt cơm.</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào button thêm hoặc hủy trong khung từng món ăn.
        </td>
        <td>- Lấy thông tin. <br/>- Nếu số lượng hợp lệ, thêm món ăn vào giỏ hàng hoặc xóa món ăn khỏi giỏ hàng. Ngược lại trả về thông báo lỗi cho người dùng.
        </td>
    </tr>
</table>

**8.2 View Detail Material**

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào trang nguyên liệu </td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút xem chi tiết mà chuyển trang hoặc tắt trình duyệt , use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng tìm xem chi tiết nguyên liệu: tên, giá cả, thể loại , mô tả,...  </td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- nhấn vào xem chi tiết của nguyên liệu cụ thể</td>
        <td>- Lấy thông tin nguyên liệu trong cơ sở dữ liệu.<br/>
        -nếu thành công trả về trang chi tiết nguyên liệu, ngược lại thông báo lỗi.
        </td>
    </tr>
</table>

**8.3 Choose Material

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đang ở trạng thái đăng nhập ứng dụng</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"></td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Thêm hoặc hủy nguyên liệu vào giỏ hàng đi chợ.</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào button thêm hoặc hủy trong khung từng nguyên liệu.
        </td>
        <td>- Lấy thông tin. <br/>- Nếu số lượng hợp lệ, thêm nguyên liệu vào giỏ hàng hoặc xóa nguyên liệu khỏi giỏ hàng. Ngược lại trả về thông báo lỗi cho người dùng.
        </td>
    </tr>
</table>

**Comment by ghost** [comment]
- use-case have to be the verbs.
- miss CRUD functions
- miss search function
- you should split up use-case

**Comment by dungvan** [comment]
check my update please!

**Comment by ghost** [comment]
-why don't have use-case login?
-use-case manage daily menu, manage material, manage order diagrams are wrong.
-you have to add specific description document.
-you should add a overview use-case diagram.
