### ISSUE TITLE
Admin - Manage Daily Menu - Delete Menu 

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#30]
![admindeletemenu](https://user-images.githubusercontent.com/26675245/28651077-c996ccb4-72a9-11e7-83b3-8b755bb4f3d0.jpg)

**Comment by hungbkdn** [comment]
![admindeletemenu](https://user-images.githubusercontent.com/26675245/28653852-2d873fe6-72ba-11e7-806c-fb6d2427766d.jpg)

**Comment by ghost** [comment]
-(2) should be outer fragment.
-(3) should be an action.
-(5) don't  return from Model to View.

**Comment by hungbkdn** [comment]
![adminDeleteMenu.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46e990972a8ca7ac83ecab468958fe816b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d86b7b68b49c0e93823e08a884d3e1a0c0ac4.jpg)
I updated, please check it again
Thank you so much

**Comment by ghost** [comment]
LGTM.
