### ISSUE TITLE
Guest Search Materials

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#31]
![guestSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ef819f3096b0ac8efbbc4b895ce4913b4f267f3a46ef696097ec22ba416f43554d4ba5470c5945adacdc7af0e038768a5c0abc876a0c26906c03b0aac04ee155e57dd205d0f4ae805ec3e93724e28b8e4a3b1b031d8cf65b3db2d4.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-You should change onClick(): Search to onClick()
-I don't understand get(id: int, isFood: boolean).
-remove Display result function.

**Comment by ghost** [comment]
-change Lifeline2:Guest to :Guest, GUI:MaterialList: to GUI:MaterialList.
-what will happen when (2) was error
-what's condition you search material? 
-you should validate in server.

**Comment by ghost** [comment]
-(3) should be outer fragment.
-(5) remove ().

**Comment by hungbkdn** [comment]
![guestSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ef819f3096b0ac8efbbc4b895ce4913b4f267f3a46ef696097ec22ba416f43554d4ba5470c5945adacdc7af0e038768a5c0abc876a0c26906c03b0aac04ee155e57dd205d0f4ae805ec2ee3724e28b8e4a3b18001988ff5e32b2d4.jpg)

**Comment by ghost** [comment]
-change :Materials to :Material
-(2) should be an action.
-life of GUI:MaterialList should end at (7)

**Comment by hungbkdn** [comment]
I updated, please check it again
Thank you so much
![guestSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ef819f3096b0ac8efbbc4b895ce4913b4f267f3a46ef696097ec22ba416f43554d4ba5470c5945adacdc7af0e038768a5c0abc876a0c26906c03b0aac04ee155e57dd205d0f4ae805ec3e93724e28b8e4a361c0d1e8ef85933b2d4.jpg)

**Comment by ghost** [comment]
-:Guest change to actor symbol

**Comment by hungbkdn** [comment]
![guestSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46ef819f3096b0ac8efbbc4b895ce4913b4f267f3a46ef696097ec22ba416f43554d4ba5470c5945adacdc7af0e038768a5c0abc876a0c26906c03b0aac04ee155e57dd205d0f4ae805ec3e93724e28b8e4a361a031e8cff5431b2d4.jpg)

**Comment by ghost** [comment]
Pls explain 5: what is `condition int` ?

**Comment by hungbkdn** [comment]
**Pls explain 5: what is condition int ?**
Guest and User can search material item by name, by category or by suppliers.
So we adding condition with type int has value 1, 2, 3 to check condition guest search
