### ISSUE TITLE
User Search Materials

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#32]
![userSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46fd879f31b186a89deab76ea549f58620472b606b48e13b628ae92dbc56395b4d5a47aa155e5e15a9acd87df0b23a708a5d5abbd63e0d22972f0dbefad341eb5ee779c11ac7a4b6984fc1e23c20e78a8a4a3b19011c88f95527ed.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-why don't you validate data in server?
-what criteria will you search?
-I think you should remove display result function.

**Comment by hungbkdn** [comment]
I updated GUI:viewName, criteria to search and remove display result
I validate in GUI because it just check value of search, if it null will not send request to server

**Comment by ghost** [comment]
-what's condition you search material?
-you should validate in server.

**Comment by ghost** [comment]
-(3) should be outer fragment.
-(5) remove ().

**Comment by hungbkdn** [comment]
![userSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46fd879f31b186a89deab76ea549f58620472b606b48e13b628ae92dbc56395b4d5a47aa155e5e15a9acd87df0b23a708a5d5abbd63e0d22972f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78a8a4a381b06198ff65c27ed.jpg)

**Comment by ghost** [comment]
-change :Materials to :Material
-(2) should be an action.
-life of GUI:MaterialList should end at (7)

**Comment by hungbkdn** [comment]
I updated, please check it again
Thank you so much
![userSearchMaterials.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46fd879f31b186a89deab76ea549f58620472b606b48e13b628ae92dbc56395b4d5a47aa155e5e15a9acd87df0b23a708a5d5abbd63e0d22972f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78a8a4838190c1e80fa5827ed.jpg)

**Comment by ghost** [comment]
LGTM
