### ISSUE TITLE
User - Order Food

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#33]
![foodcreate](https://user-images.githubusercontent.com/19891027/28513643-1004738e-7081-11e7-9e18-b75a7b2c1abb.jpg)

**Comment by dnkTin** [comment]
I updated, please review it!
![foodcrerate](https://user-images.githubusercontent.com/19891027/28654298-6227d776-72bd-11e7-9ac7-e7d41d64a7dd.jpg)

**Comment by ghost** [comment]
@at-dungvan 
- `Choose Food Create` the name isn't good, please thinking about this and make clearly.
- Re-design this UML because it's not correctly.

**Comment by dungvan** [comment]
![order-food.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46e7869e2690ceaf80e6bb01e81fe086264c22703d46f96925dcb52ce9137a040a0e18fa455e5f44fda8df2cf5e46a21984019af80330b2b9b645bf9fa9015ad03bc2a8a4a85b7b9824ec0e03c23e5829d02.jpg)

**Comment by ghost** [comment]
LGTM
