### ISSUE TITLE
Admin Module-Delete User

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#34]

**Comment by at-duyho** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-You should change Local storage to Model.
-why you deleted it but you return message confirm?

**Comment by at-tindang** [comment]
I updated it, please check again!

**Comment by at-duyho** [comment]
-why view call to Model?

**Comment by at-tindang** [comment]
I updated! Please review.
![fooddelete](https://user-images.githubusercontent.com/19891027/28654319-8b7b3c44-72bd-11e7-9214-8ca38c93db3f.jpg)

**Comment by at-duyho** [comment]
-I think you should ask team members support you. Thank you!
