### ISSUE TITLE
Admin Module-Search

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#35]

**Comment by at-duyho** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-You should change Local storage to Model.

**Comment by at-tindang** [comment]
I updated it, please check again! 
I mean: When user click add button, firstly data save to local storage and when user confirm order, it will be saved to db

**Comment by at-duyho** [comment]
-why view call to Model?

**Comment by at-tindang** [comment]
I updated! Please reiview.
![materialcreate](https://user-images.githubusercontent.com/19891027/28654340-abb22b94-72bd-11e7-9037-074bf9c395c5.jpg)

**Comment by at-duyho** [comment]
- you should ask team members to support you. thank you!
