### ISSUE TITLE
User  0rder  Material

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#36]
![materialdelete](https://user-images.githubusercontent.com/19891027/28554221-79e5cff4-7122-11e7-92d4-7b1b34cbea1b.jpg)

**Comment by ghost** [comment]
-You should add new a controller
-you should change local storage:Cart to :Cart

**Comment by dnkTin** [comment]
![materialdelete](https://user-images.githubusercontent.com/19891027/28654375-eea33f92-72bd-11e7-8a6d-f1b2d45a8afb.jpg)

**Comment by vhhieu95** [comment]
![userordermaterial.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46fd879f318d91ad8afbb242b058e29d284a653f6b14b1247a80e03cfd18395456591aaa40090a11adafdf2fa0b63c71db0a0cbe833b0e66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d24e2838f473e1e05118ced10.jpg)

**Comment by at-duyho** [comment]
LGTM.

**Comment by ghost** [comment]
-set name for fragment loop.

**Comment by vhhieu95** [comment]
![userordermaterial2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecac3ca1a9d001a112f61/125516c66e82c728ace21e0d46fd879f318d91ad8afbb242b058e29d284a75316546b3397f8fe62bab0021435a5648f847590e11a9a8df7da2b03c708b0d5dea823f0925d42103eee9dc4be05ce36ade0d97bcae884acae93825e68e874c3c1f041f8cfc4f78.jpg)
please check my update again, thank you!

**Comment by ghost** [comment]
LGTM
