### ISSUE TITLE
Class-diagram

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#38]

**Comment by at-vudang95** [comment]
![classdiagram.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46eb989b309187a08eeead42a91fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8a44c8eb3e24e48b8c472c53.jpg)

**Comment by ghost** [comment]
-I think you should create Customer and Admin model extend from User?
-Create Food and Material model extend from Item.
-Create Relationships, you should refer link: https://en.wikipedia.org/wiki/Class_diagram

**Comment by at-vudang95** [comment]
![classdiagram.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46eb989b309187a08eeead42a91fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8a45c5e93a24e2828f4f2c53.jpg)
I just updated. Please, you check again!

**Comment by ghost** [comment]
-item use category? Item Model contain list categories?

**Comment by at-vudang95** [comment]
![classdiagram.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46eb989b309187a08eeead42a91fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8b49c8eb3a2de78b8f482c53.jpg)
I updated. Please check it again. Thank you!

**Comment by ghost** [comment]
LGTM.
