### ISSUE TITLE
not in use

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#39]

**Comment by at-duyho** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-remove alert(), display functions.
-what happen when actor call clickOrderButton function?
- I don't understand combined Framgemt1
-(6) save function should be call by Oder model.

**Comment by at-tindang** [comment]
I updated it, please check again!

**Comment by at-duyho** [comment]
-what's information you will confirm order?
-you should show follow from choose food to confirm order.
-remove display functions.
-what's (11).

**Comment by at-tindang** [comment]
I updated! Please review.
![orderconfirm](https://user-images.githubusercontent.com/19891027/28654383-085da738-72be-11e7-90fb-a50d16d89d22.jpg)

**Comment by at-duyho** [comment]
-(3) should be same (10)
