### ISSUE TITLE
Admin Module-Detail User

### ISSUE THREAD

**Issue by dnkTin** [AT-PHPIntership/food-market-order#40]

**Comment by at-duyho** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-(2)return Oder: view call by itself?
-replace alert function by confirm framgmemt.
-I don't understand follow (7), (8), (9) and (10)

**Comment by at-tindang** [comment]
I updated it, please check again!

**Comment by at-duyho** [comment]
-you should validate data.
-change Model:Order to :Order.

**Comment by at-tindang** [comment]
I updated! Please review
![ordercancel](https://user-images.githubusercontent.com/19891027/28654454-ab1b8da0-72be-11e7-952e-57710ded4893.jpg)

**Comment by at-duyho** [comment]
- what's alt CombinedFragment1?
-why you don't validate in server?
