### ISSUE TITLE
Admin - Delete order - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#41]

**Comment by at-vudang95** [comment]
![DeleteOrder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cc9196269686869dedba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b826814e80b6bd8b4ec7ef342de4888e5d73.jpg)

**Comment by ghost** [comment]
-change :Admin to actor symbol.
-what's Order object fragment? I don't understand this fragment.

**Comment by at-vudang95** [comment]
![deleteorder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46ec9196269686a69dedba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b826814e80b6bd8f4bc7e93525ee8a8d5d73.jpg)
I mistake. Pleased check it again. Thank you!

**Comment by ghost** [comment]
LGTM
