### ISSUE TITLE
Admin - Create category - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#42]

**Comment by at-vudang95** [comment]
![CreateCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cb869f2296868a8efdba4fab5ae9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc0ed342cef8e8c493a1f1755.jpg)

**Comment by ghost** [comment]
-you should change admin1:Admin to :Admin, category:Category to :Category
-you should change managerCategory:Page to GUI:<viewName>
-you have to dissociation WebServer to multi object.
-you should define methods with params in sequence diagram.

**Comment by at-vudang95** [comment]
![CreateCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cb869f2296868a8efdba4fab5ae9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0ee3f27e0898a4c39181755.jpg)
I updated. Please you check again!

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-in a sequence diagram can use more than one view.
-remove display functions.
-(13) should be call by Category model.
-remove connect database fragement.

**Comment by at-vudang95** [comment]
![CreateCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cb869f2296868a8efdba4fab5ae9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc0e03f23ef828f4b3a161755.jpg)
I updated, please you check again, thank you!

**Comment by ghost** [comment]
-why create Category from :OrderController?
-what will happen whe (10) error?

**Comment by at-vudang95** [comment]
Sorry I mistake :OrderController. Please you check again! Thank you!
![CreateCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cb869f2296868a8efdba4fab5ae9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1e93f23ef8a8b4e3b1d1755.jpg)

**Comment by ghost** [comment]
-(6), (14) should be same (3)

**Comment by at-vudang95** [comment]
![createcategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46eb869f229686aa8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ed3823ef8b87483a171755.jpg)
Please you check again! Thank you!

**Comment by ghost** [comment]
@at-vudang i think that we should group (7) and (8) to only once.

**Comment by at-vudang95** [comment]
![createcategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46eb869f229686aa8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ed3a20e5838f49371f1755.jpg)
I updated. @at-locbui  please check it again! Thank you

**Comment by ghost** [comment]
@at-vudang missing step 9

**Comment by at-vudang95** [comment]
![createcategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46eb869f229686aa8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ed3521e48e864c3a181755.jpg)
I updated. Please check it again. Thank you

**Comment by ghost** [comment]
LGTM
