### ISSUE TITLE
Admin - Update category - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#43]

**Comment by at-vudang95** [comment]
![UpdateCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46dd849e2296868a8efdba4fab5ae9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1e93f22e18e8a46361e1755.jpg)

**Comment by ghost** [comment]
-change :Admin to actor symbol.
-group (9) and (10)
-(6) get list or get an object?

**Comment by at-vudang95** [comment]
![updatecategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fd849e229686aa8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ed3525e58e8a463e1d1755.jpg)
I updated. Please check it again. Thank you!

**Comment by ghost** [comment]
LGTM

**Comment by ghost** [comment]
4: Update
Why user click on button Add?

**Comment by at-vudang95** [comment]
Sorry I mistake. I updated. Please check it again. Thank you!
![updatecategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46fd849e229686aa8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ee3e2de58d8d4f3d1f1755.jpg)

**Comment by ghost** [comment]
`10: Save Category(data)` 
I think you should change to `sendData()` and `11: checkValidation()`
`13: boolean save()` change to `13: save()`

**Comment by at-vudang95** [comment]
![UpdateCategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46dd849e2296868a8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ee3921e28886483c181755.jpg)
I updated. Please check it again. Thank you!
