### ISSUE TITLE
Admin - Delete category - Sequence diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#44]

**Comment by at-vudang95** [comment]
Sequence Diagram - Use Case - Delete Category
![DeleteCatelogy.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cc91962696868a8efdba4fab5ae9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0e13827ef8c864e3e1d1755.jpg)

**Comment by ghost** [comment]
@at-vudang 
- please separate :OrderController and :Category
- What is happen (9) after delete?

**Comment by at-vudang95** [comment]
![deletecategory.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46ec9196269686aa8efdba44ab4fe9d665043761260ea62864c7b96aea1b2d05595e1ff914090912f8ff892ba7e76a77d90e5dbcc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ed3a20e08f884737181755.jpg)
I updated. Please you check it again.

**Comment by ghost** [comment]
LGTM
