### ISSUE TITLE
Admin create user sequence diagram

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#45]
sequence diagram

**Comment by dungvan** [comment]
![create-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46eb869f229686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bc8348c8e93924e2828d5d73.jpg)

**Comment by ghost** [comment]
-why don't you check validate in server?
-remove (12) and fragment result query, it is not necessary.

**Comment by dungvan** [comment]
![create-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46eb869f229686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b826814e80b6bc8348c8ea3a25e282865d73.jpg)
- i updated this sequence, please check again!
- to keep performance of server, i think we should check validate by javascript in browser client

**Comment by ghost** [comment]
-remove (6).
-what will happen (10) was error?

**Comment by dungvan** [comment]
![Model1__Collaboration1__Interaction1__Admin create user_2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46c59b9e268ed296b0cab04fa85cf29b3b47337a260af2144faced3cba507a021b0611f240373035a8a4d075b6e57e25db185efd942e0a36a93f03b0aac25de05bef73cf5d8fa4b9834a94ee3c74b2dede19681a031889fe0c63a7ca199e09e457f30f04fa47693ebf3c633e559e0c762d616623abfdde578e8d66a7b917264485.jpg)

please check my update again, thank you!

**Comment by ghost** [comment]
-(9) should be outer fragment check result.
-(2) should be an action

**Comment by dungvan** [comment]
![create-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46eb869f229686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8f4bc4ee3520e78d895d73.jpg)

**Comment by ghost** [comment]
-life of model User should end at (10).
-(6) should be outer fragment.

**Comment by dungvan** [comment]
![create-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46eb869f229686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8f4bc7e03e25e2888b5d73.jpg)

**Comment by ghost** [comment]
-(3) should return to GUI:CreateUser

**Comment by dungvan** [comment]
![create-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46eb869f229686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8c4fc8ec392ce48e885d73.jpg)

I updated, please check again, thanks!

**Comment by ghost** [comment]
LGTM
