### ISSUE TITLE
Admin read user sequence diagram

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#46]
sequence diagram

**Comment by dungvan** [comment]
![detail-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec918e228b8fe49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8b4ec7e93e22ee888d5d73.jpg)

**Comment by ghost** [comment]
-Don't GUI:DetailUser use?
-(2) should be an action

**Comment by dungvan** [comment]
![detail-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec918e228b8fe49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b826814e80b6bd8f4bc4ef3424ef828f5d73.jpg)

**Comment by ghost** [comment]
@at-dungvan you didn't update anything, please check latest comment. Thank you!

**Comment by dungvan** [comment]
![detail-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec918e228b8fe49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8f44c4ef392de18f8e5d73.jpg)

I updated, please check again, thank you!

**Comment by ghost** [comment]
LGTM
