### ISSUE TITLE
Admin delete user sequence diagram

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#48]
sequence diagram

**Comment by dungvan** [comment]
![delete-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec9196269686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8b4ec7e93b2de78b8e5d73.jpg)

**Comment by ghost** [comment]
LGTM

**Comment by ghost** [comment]
Why don't check has permission or not for delete user ?

**Comment by dungvan** [comment]
delete user from admin page, of course that the user login is admin, so we not need to check permission

**Comment by ghost** [comment]
On view of list user was show list users on systems? How about if user admin have ID: 1 and click on button delete current account? What happen will occur ?

**Comment by dungvan** [comment]
Ok! i understand this problems, so i have to check that ID is not user admin before i delete that id from database. Thank you!

![delete-user](https://user-images.githubusercontent.com/11406553/28837114-cfb33e32-7715-11e7-92af-9fbb08033ed4.jpg)

**Comment by dungvan** [comment]
![delete-user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec9196269686e49afaba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8c4fc8ea3526e18b8a5d73.jpg)

**Comment by ghost** [comment]
LGTM, Thanks
