### ISSUE TITLE
User-Guest read detail food sequence diagram

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#49]
sequence diagram

**Comment by dungvan** [comment]
![read-food](https://user-images.githubusercontent.com/11406553/28511405-479a6de4-7077-11e7-9c00-b807420b8f03.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-I don't understand alt fragment.
-I don't understand follow (7), (13), (8), (11), (10)

**Comment by dungvan** [comment]
![detail-food.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec918e228b8fe489e6b047e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b826814e80b6bc8348c8eb3822e1828b5d73.jpg)

- i updated this sequence, please check again!

**Comment by ghost** [comment]
-(5) return from Model to view?

**Comment by dungvan** [comment]
![Guest-detail-food.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46cf819f3096cead8afdbe4aa810f69b2642653f6b14b1247a80e03cfd18395456591aaa40090a11adafdf2fa0b63c71db0a0cbe833b0e66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d24e28c8b4737180c1088ed10.jpg)

**Comment by ghost** [comment]
LGTM
