### ISSUE TITLE
User-Guest read detail material sequence diagram

### ISSUE THREAD

**Issue by dungvan** [AT-PHPIntership/food-market-order#50]
sequence diagram

**Comment by dungvan** [comment]
![read-material](https://user-images.githubusercontent.com/11406553/28511427-66fd4abc-7077-11e7-9b2b-62de91ee1ae1.jpg)

**Comment by ghost** [comment]
-remove fragment result query, (5), (10)

**Comment by ghost** [comment]
-please update it, follow another issue

**Comment by dungvan** [comment]
![detail-material.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ec918e228b8fe482e8ab46b654f1986b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d86b7b68b49c0e93c27e0898f4a3619000ac4.jpg)
please check my update again! thank you!

**Comment by ghost** [comment]
-(2) should be an action.
-Is actor user or guest?

**Comment by dungvan** [comment]
![guest-detail-material.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecae2457beb001f4c5ea1/125516c66e82c728ace21e0d46ef819f3096cead8afdbe4aa810fd953d43357a2808e1673295f127b54778154d555ca9485e0b42fda8dc7ef7e06a748c5c0bec803b5827946b40bea4905dee5fee7fd616cfe3fe9846d2eb3c2fe68e8f4e3b19051e8cf95f30a18b06.jpg)

**Comment by ghost** [comment]
LGTM.
Thanks. (y)
