### ISSUE TITLE
Guest - Login - Sequence Diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#51]

**Comment by at-vudang95** [comment]
![Login.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46c49b9d2a8cc1e5cdf9ad4cae58f3806b1c65267052a77d2184e62dbe447d55595f4ead100e5817aeafd839baa47e21d40854b088270a36d43703aebe881eba01ba26894b80b4b9824dc5fa70.jpg)

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-you remove display functions
-Remove fragment connect database

**Comment by at-vudang95** [comment]
I just updated. Please you check again!
![Login.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46c49b9d2a8cc1e5cdf9ad4cae58f3806b1c65267052a77d2184e62dbe447d55595f4ead100e5817aeafd839baa47e21d40854b088270a36d43703afb9881eba01bb2189488cb7bc894bc6fa70.jpg)

**Comment by ghost** [comment]
-what will happen when (8) error?

**Comment by at-vudang95** [comment]
![login.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46e49b9d2a8cc1e5cdf9ad4cae58f3806b1c65267052a77d2184e62dbe447d55595f4ead100e5817aeafd839baa47e21d40854b088270a36d43703afb9881eba01bb258c4687b0b98244c7fa70.jpg)
I update. Please check it again. Thank you!

**Comment by ghost** [comment]
-In this case you should define follow for error and success. For example:
if error return to Login page, success return to Home page

**Comment by at-vudang95** [comment]
![login.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46e49b9d2a8cc1e5cdf9ad4cae58f3806b1c65267052a77d2184e62dbe447d55595f4ead100e5817aeafd839baa47e21d40854b088270a36d43703afb9881eba01bb25834b87b7bd8f4fc7fa70.jpg)
I updated. Please check it again. Thank you!

**Comment by ghost** [comment]
@at-vudang Guest user can't login to system. Only user who already has account can login the system.

**Comment by at-vudang95** [comment]
![login.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46e49b9d2a8cc1e5cdf9ad4cae58f3806b1c65267052a77d2184e62dbe447d55595f4ead100e5817aeafd839baa47e21d40854b088270a36d43703aebe881eba01bb25834a86bfb5824cc9fa70.jpg)
I updated. Please check it again. Thank you!

**Comment by ghost** [comment]
LGTM
