### ISSUE TITLE
Admin - Confirm Order - Sequence Diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#52]

**Comment by at-vudang95** [comment]
![ConfirmOrder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cb9b94258b91a4a0fbbb46b61fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8a45c5eb3c27e48c8a4b2c53.jpg)

**Comment by ghost** [comment]
-:Admin change to actor symbol.
-I don't understand fragment Object order.

**Comment by at-vudang95** [comment]
![ConfirmOrder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cb9b94258b91a4a0fbbb46b61fbcd6395428792c07b7692ac7b671e9462d500e0a1bfd170e5b42fcf9887af0b16f22dc0d19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8b4ac3ef3a22e48e894c2c53.jpg)
I updated. Pleased check it again! Thank you!

**Comment by ghost** [comment]
-Confirm order in ViewManagerOrder or in a new other view? I need feedback from you. thank you!

**Comment by at-vudang95** [comment]
Have a button Confirm Order in list order of ViewManageOrder.

**Comment by ghost** [comment]
Thank you! LGTM.
