### ISSUE TITLE
Admin - Filter Order - Sequence Diagram

### ISSUE THREAD

**Issue by at-vudang95** [AT-PHPIntership/food-market-order#53]

**Comment by at-vudang95** [comment]
![FilterOrder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46ce9d96378791869dedba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bc8c4ec5ec3c25e3888c5d73.jpg)

**Comment by ghost** [comment]
-:Admin change to actor symbol
-(8), (15) should be in Model.
-remove display functions.
-group (4) and (11)

**Comment by at-vudang95** [comment]
![filterorder.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46ee9d96378791a69dedba51e611b2843b492d762a10e17132d0ba7ebb142a000a0a1ffa175c5944fcf8d87da1e56e26db4e17ff933c0120996048e6edc00db513b921814e80b6bd8f4bc8ec3f22e38c8a5d73.jpg)
I update. Please check it again. Thank you!

**Comment by ghost** [comment]
LGTM

**Comment by ghost** [comment]
How about filter order by Order ID ?
