### ISSUE TITLE
Admin - Manage Daily Menu - Create Menu

### ISSUE THREAD

**Issue by hungbkdn** [AT-PHPIntership/food-market-order#9]

**Comment by hungbkdn** [comment]
![admincreatemenu](https://user-images.githubusercontent.com/26675245/28650284-ed3008ac-72a4-11e7-92e1-c9333fcc4024.jpg)

**Comment by ghost** [comment]
-you should change admin:Admin to :Admin, menu:Menu to :Menu
-you should change createmenu:View to GUI:<nameView>
-you have to dissociation WebServer to multi object.

**Comment by ghost** [comment]
-I'm sorry, I have a mistake: you change :GUI to GUI:viewName. please change it. thank you.
-I think you should remove displayError function.
-remove frame check unique date because you check by validate function.

**Comment by ghost** [comment]
-You should change GUI:manageMenu: to GUI:manageMenu
-(6) should be outside fragment validate.

**Comment by hungbkdn** [comment]
![admincreatemenu](https://user-images.githubusercontent.com/26675245/28654134-27775bca-72bc-11e7-902d-0ed8b352382f.jpg)

I updated, please check my comment!
Thank you so much

**Comment by ghost** [comment]
-(3), (11) should be same (7).

**Comment by hungbkdn** [comment]
![adminCreateMenu.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edf63457beb001f4c5eb3/125516c66e82c728ace21e0d46e990972a8ca0bb8ae8ab468958fe816b0a65633b0ba92e7391a172fd1722570b594ffd140d0e12aafd8f2ba6b76d268d0f59bb807f4366846c4ff8e7df46f554f832815d86b7b68b49c0e93820e1888b483f1e040ac4.jpg)
I updated, please check again
Thank you so much

**Comment by ghost** [comment]
LGTM
